In [231]:
#1) Write a program to create a 5 dimensional array with all zeros and ones

In [232]:
import numpy as np 

In [233]:
y=np.zeros((2,1,4,2,3),dtype=int)

In [234]:
y

array([[[[[0, 0, 0],
          [0, 0, 0]],

         [[0, 0, 0],
          [0, 0, 0]],

         [[0, 0, 0],
          [0, 0, 0]],

         [[0, 0, 0],
          [0, 0, 0]]]],



       [[[[0, 0, 0],
          [0, 0, 0]],

         [[0, 0, 0],
          [0, 0, 0]],

         [[0, 0, 0],
          [0, 0, 0]],

         [[0, 0, 0],
          [0, 0, 0]]]]])

In [235]:
#ones

In [236]:
w=np.ones((2,1,4,2,3),dtype=int)

In [237]:
w

array([[[[[1, 1, 1],
          [1, 1, 1]],

         [[1, 1, 1],
          [1, 1, 1]],

         [[1, 1, 1],
          [1, 1, 1]],

         [[1, 1, 1],
          [1, 1, 1]]]],



       [[[[1, 1, 1],
          [1, 1, 1]],

         [[1, 1, 1],
          [1, 1, 1]],

         [[1, 1, 1],
          [1, 1, 1]],

         [[1, 1, 1],
          [1, 1, 1]]]]])

In [238]:
#2) Write a program to create an array of 10 zeros,10 ones, and 10 fives in row 1 2 and 3 which create a new array of shape (3,10)

In [239]:
import numpy as np

In [240]:
x=np.array([np.zeros(10),np.ones(10),np.full(10,5)])

In [241]:
x

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]])

In [242]:
#3) Write a program to create a 3x4 matrix filled with values from 10 to 21.

In [243]:
w=np.arange(10,22).reshape(3,4)

In [244]:
w

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [245]:
#4) Write a  program to create a 10x10 zero matrix with elements on the main diagonal equal to 0,1,2,3,4,5,6,7,8,9,

In [246]:
x=np.diag([0,1,2,3,4,5,6,7,8,9])

In [247]:
x

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 9]])

In [248]:
#5) Write a program to create a 4x4 array. Create an array from below array by swapping first and last, second and third columns.

In [249]:
x=np.array([[1,2,3,4,],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

In [250]:
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [251]:
x[::-1,::]

array([[13, 14, 15, 16],
       [ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [252]:
#6) Write a program to reverse an array (the first element becomes the last)

In [253]:
x=np.arange(12,28)

In [254]:
x

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [255]:
x[::-1]

array([27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12])

In [256]:
#7) Write a program to access all the elements greater than 30 and less than 80 and multiples of 5 from an array of shape 10,10 .Elements range from 1 to 100

In [257]:
x=np.arange(1,101).reshape(10,10)

In [258]:
w=x[(x>30)&(x<80)&(x%5==0)]

In [259]:
w

array([35, 40, 45, 50, 55, 60, 65, 70, 75])

In [260]:
#8) Write a program to create a 2D array with 1 on the border and 0 inside.

In [261]:
x=np.ones((4,5))

In [262]:
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [263]:
x[1:-1,1:-1]=0

In [264]:
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [265]:
#9) Write a program to create a checkerboard pattern .Don't use default array function

In [266]:
print("checkerboard: \n")
c=np.ones((8,8),dtype=int)

checkerboard: 



In [267]:
c

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [268]:
c[1::2,::2]=0
c[::2,1::2]=0

In [269]:
c

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [270]:
#10) Write a program to find common values between two arrays.

In [271]:
i=0
w=np.array([10,20,40,60])
z=np.array([10,30,40,50])
np.intersect1d(z,w)

array([10, 40])

In [272]:
#11) Write a program to create an array 2d array and then reshape into 1d array

In [273]:
x=np.arange(1,5).reshape(2,2)

In [274]:
x

array([[1, 2],
       [3, 4]])

In [275]:
x.flatten()

array([1, 2, 3, 4])

In [276]:
#12) Write a user defined function for creating a 1 or 2d array from scratch without using array functions

In [282]:
def array_2d(x):
    n=int(input("enter the dimention: "))
    s=len(x)
    if n==1:
        print("array({})".format(x))
    elif n==2:
        print("array([",end="")
        print("[{}]".format(x[0]))
        for y in range(1,s-1):
            print("     [{}]".format(x[y]))
        for y in range(s-1,s):
            print("       [{}]".format(x[y],end=""))
            print("])")
l=[]
k=int(input("enter no of elements: "))
for i in range(k):
    a=input("enter the element: ")
    l.append(a)
print(l)
array_2d(l)

enter no of elements: 4
enter the element: 7
enter the element: 6
enter the element: 5
enter the element: 4
['7', '6', '5', '4']
enter the dimention: 2
array([[7]
     [6]
     [5]
       [4]
])
