In [16]:
import numpy as np

In [17]:
w=np.genfromtxt(r"C:\Users\user\Downloads\train_extended.csv",delimiter=",",skip_header=1)

In [18]:
w

array([[ 1.575     ,  1.225     ,  0.375     , ...,  6.3219385 ,
         9.63883   , 10.        ],
       [ 1.2375    ,  1.        ,  0.375     , ...,  3.798833  ,
         7.654365  , 19.        ],
       [ 1.45      ,  1.1625    ,  0.4125    , ...,  7.01650125,
         7.257472  , 11.        ],
       ...,
       [ 1.125     ,  0.9125    ,  0.2875    , ...,  1.984465  ,
         3.118445  ,  7.        ],
       [ 1.625     ,  1.275     ,  0.4125    , ...,  7.86698625,
        10.489315  , 11.        ],
       [ 1.5875    ,  1.25      ,  0.3875    , ...,  7.38504475,
         8.788345  , 11.        ]])

In [19]:
length=w[:,0:1]

In [20]:
length

array([[1.575 ],
       [1.2375],
       [1.45  ],
       ...,
       [1.125 ],
       [1.625 ],
       [1.5875]])

In [21]:
diameter=w[:,1:2]

In [22]:
diameter

array([[1.225 ],
       [1.    ],
       [1.1625],
       ...,
       [0.9125],
       [1.275 ],
       [1.25  ]])

In [23]:
height=w[:,2:3]

In [24]:
height

array([[0.375 ],
       [0.375 ],
       [0.4125],
       ...,
       [0.2875],
       [0.4125],
       [0.3875]])

In [25]:
weight=w[:,3:4]

In [26]:
weight

array([[31.22697425],
       [21.885814  ],
       [28.25027675],
       ...,
       [10.886208  ],
       [33.89182725],
       [34.37376875]])

In [27]:
shuckedw=w[:,4:5]

In [28]:
shuckedw

array([[12.303683  ],
       [ 7.654365  ],
       [11.12717875],
       ...,
       [ 4.9044635 ],
       [13.19669225],
       [17.22232125]])

In [29]:
visceraw=w[:,5:6]

In [30]:
visceraw

array([[6.3219385 ],
       [3.798833  ],
       [7.01650125],
       ...,
       [1.984465  ],
       [7.86698625],
       [7.38504475]])

In [31]:
shellw=w[:,6:7]

In [32]:
shellw

array([[ 9.63883 ],
       [ 7.654365],
       [ 7.257472],
       ...,
       [ 3.118445],
       [10.489315],
       [ 8.788345]])

In [33]:
age=w[:,7:8]

In [34]:
age

array([[10.],
       [19.],
       [11.],
       ...,
       [ 7.],
       [11.],
       [11.]])

In [35]:
#1. max and min length
np.max(w)

80.10151225

In [36]:
np.min(w)

0.0

In [37]:
#2. Difference between max and min length
np.max(w)-np.min(w)

80.10151225

In [38]:
#3. column wise average
np.average(w,axis=0)

array([ 1.31244808,  1.02032036,  0.34602787, 23.12343631,  9.98937025,
        4.99318096,  6.63422915,  9.950615  ])

In [39]:
#4. find out the whose height is greater than 0.4
age

array([[10.],
       [19.],
       [11.],
       ...,
       [ 7.],
       [11.],
       [11.]])

In [40]:
[height>0.4]

[array([[False],
        [False],
        [ True],
        ...,
        [False],
        [ True],
        [False]])]

In [41]:
age[height>0.4]

array([11., 14., 13., ..., 11., 11., 11.])

In [42]:
#5. Average height and weight whose age=10

In [43]:
age

array([[10.],
       [19.],
       [11.],
       ...,
       [ 7.],
       [11.],
       [11.]])

In [44]:
a=height[age==10]

In [45]:
a

array([0.375 , 0.4   , 0.3375, ..., 0.3125, 0.3875, 0.3875])

In [46]:
np.average(a)

0.3833672856539947

In [47]:
b=weight[age==10]

In [48]:
b

array([31.22697425, 28.33532525, 18.313777  , ..., 26.18076325,
       30.46153775, 34.9549335 ])

In [49]:
np.average(b)

28.243308450511314

In [50]:
#6. total shell weight

In [51]:
shellw

array([[ 9.63883 ],
       [ 7.654365],
       [ 7.257472],
       ...,
       [ 3.118445],
       [10.489315],
       [ 8.788345]])

In [52]:
np.sum(shellw)

1326845.8295214002

In [53]:
#7. how many persons belong to each and every unique age
a=np.unique(age)

In [106]:
age=w[:,7]
np.unique(age,return_counts=True)

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
        27., 29.]),
 array([   46,    42,   625,  2787,  5475, 12450, 18276, 26818, 32906,
        30803, 23457, 12717, 10037,  6352,  4831,  3191,  2705,  1953,
         1591,  1206,   721,   296,   352,   110,    51,    46,    99,
           57], dtype=int64))

In [55]:
#8. Difference shucked weight and viscera weight 
shuckedw

array([[12.303683  ],
       [ 7.654365  ],
       [11.12717875],
       ...,
       [ 4.9044635 ],
       [13.19669225],
       [17.22232125]])

In [61]:
visceraw

array([[6.3219385 ],
       [3.798833  ],
       [7.01650125],
       ...,
       [1.984465  ],
       [7.86698625],
       [7.38504475]])

In [62]:
shuckedw-visceraw

array([[5.9817445],
       [3.855532 ],
       [4.1106775],
       ...,
       [2.9199985],
       [5.329706 ],
       [9.8372765]])

In [63]:
#9. Average height of a person whose age between 14 & 19

In [110]:
x=w[w[:,7]>14]
y=x[x[:,7]<19]
z=y[:,3]

In [111]:
np.mean(z)

32.11337167476735

In [66]:
#10. what is average weight if include shuckedw weight,viceraw and shell weight
x=np.average(shellw)

In [67]:
x

6.634229147607001

In [68]:
y=np.average(shuckedw)

In [69]:
y

9.989370248049001

In [70]:
z=np.average(visceraw)

In [71]:
z

4.993180956748749

In [72]:
(x+y+z)/3

7.205593450801583

In [73]:
# second sheet

In [74]:
y=np.genfromtxt(r"C:\Users\user\Downloads\tipsf (1).csv",delimiter=",",skip_header=1)

In [75]:
y

array([[  0.  ,  16.99,   1.01, ...,   1.  ,   0.  ,   2.  ],
       [  1.  ,  10.34,   1.66, ...,   1.  ,   0.  ,   3.  ],
       [  2.  ,  21.01,   3.5 , ...,   1.  ,   0.  ,   3.  ],
       ...,
       [241.  ,  22.67,   2.  , ...,   0.  ,   0.  ,   2.  ],
       [242.  ,  17.82,   1.75, ...,   0.  ,   0.  ,   2.  ],
       [243.  ,  18.78,   3.  , ...,   2.  ,   0.  ,   2.  ]])

In [76]:
totalbill=y[:,1:2]

In [77]:
totalbill

array([[16.99],
       [10.34],
       [21.01],
       [23.68],
       [24.59],
       [25.29],
       [ 8.77],
       [26.88],
       [15.04],
       [14.78],
       [10.27],
       [35.26],
       [15.42],
       [18.43],
       [14.83],
       [21.58],
       [10.33],
       [16.29],
       [16.97],
       [20.65],
       [17.92],
       [20.29],
       [15.77],
       [39.42],
       [19.82],
       [17.81],
       [13.37],
       [12.69],
       [21.7 ],
       [19.65],
       [ 9.55],
       [18.35],
       [15.06],
       [20.69],
       [17.78],
       [24.06],
       [16.31],
       [16.93],
       [18.69],
       [31.27],
       [16.04],
       [17.46],
       [13.94],
       [ 9.68],
       [30.4 ],
       [18.29],
       [22.23],
       [32.4 ],
       [28.55],
       [18.04],
       [12.54],
       [10.29],
       [34.81],
       [ 9.94],
       [25.56],
       [19.49],
       [38.01],
       [26.41],
       [11.24],
       [48.27],
       [20.29],
       [13.81],
       [

In [78]:
tip=y[:,2:3]

In [79]:
tip

array([[ 1.01],
       [ 1.66],
       [ 3.5 ],
       [ 3.31],
       [ 3.61],
       [ 4.71],
       [ 2.  ],
       [ 3.12],
       [ 1.96],
       [ 3.23],
       [ 1.71],
       [ 5.  ],
       [ 1.57],
       [ 3.  ],
       [ 3.02],
       [ 3.92],
       [ 1.67],
       [ 3.71],
       [ 3.5 ],
       [ 3.35],
       [ 4.08],
       [ 2.75],
       [ 2.23],
       [ 7.58],
       [ 3.18],
       [ 2.34],
       [ 2.  ],
       [ 2.  ],
       [ 4.3 ],
       [ 3.  ],
       [ 1.45],
       [ 2.5 ],
       [ 3.  ],
       [ 2.45],
       [ 3.27],
       [ 3.6 ],
       [ 2.  ],
       [ 3.07],
       [ 2.31],
       [ 5.  ],
       [ 2.24],
       [ 2.54],
       [ 3.06],
       [ 1.32],
       [ 5.6 ],
       [ 3.  ],
       [ 5.  ],
       [ 6.  ],
       [ 2.05],
       [ 3.  ],
       [ 2.5 ],
       [ 2.6 ],
       [ 5.2 ],
       [ 1.56],
       [ 4.34],
       [ 3.51],
       [ 3.  ],
       [ 1.5 ],
       [ 1.76],
       [ 6.73],
       [ 3.21],
       [ 2.  ],
       [

In [80]:
sex=y[:,3:4]

In [81]:
sex

array([[0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],

In [82]:
smoker=y[:,4:5]

In [83]:
smoker

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],

In [84]:
day=y[:,5:6]

In [85]:
day

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],

In [86]:
time=y[:,6:7]

In [87]:
time

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],

In [88]:
size=y[:,7:8]

In [89]:
size

array([[2.],
       [3.],
       [3.],
       [2.],
       [4.],
       [4.],
       [2.],
       [4.],
       [2.],
       [2.],
       [2.],
       [4.],
       [2.],
       [4.],
       [2.],
       [2.],
       [3.],
       [3.],
       [3.],
       [3.],
       [2.],
       [2.],
       [2.],
       [4.],
       [2.],
       [4.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [4.],
       [2.],
       [4.],
       [2.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [2.],
       [2.],
       [2.],
       [4.],
       [2.],
       [2.],
       [4.],
       [3.],
       [2.],
       [2.],
       [2.],
       [4.],
       [2.],
       [4.],
       [2.],
       [4.],
       [2.],
       [2.],
       [4.],
       [2.],
       [2.],
       [2.],
       [4.],
       [3.],
       [3.],
       [2.],
       [1.],
       [2.],
       [2.],
       [2.],
       [3.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],

In [90]:
#1. what is the total bill value 
a=np.sum(totalbill)

In [91]:
a

4827.77

In [92]:
#2. What is the total tip value
b=np.sum(tip)

In [93]:
b

731.5799999999999

In [94]:
#3.count how many sunday,saturday,thursday,friday are there
days=w[:,5]
x=np.unique(days,return_counts=True)
x

(array([1.41747500e-02, 2.83495000e-02, 4.25242500e-02, ...,
        2.34592112e+01, 2.52735793e+01, 2.61240642e+01]),
 array([4, 1, 3, ..., 1, 1, 1], dtype=int64))

In [95]:
#4. how many smokers are there
np.sum(smoker)

93.0

In [96]:
#5. Whatis the average tip given by female and male
np.average(tip)

2.99827868852459

In [97]:
#6. How much amount spendby male female
(a+b)/2

2779.675

In [98]:
#7. what is the max and min tip given
np.max(tip)

10.0

In [99]:
np.min(tip)

1.0

In [100]:
#8. how many male and female going for dinner and lunch
len(sex)

244

In [101]:
#9. Find out the average size
np.average(size)

2.569672131147541

In [102]:
#10. how many male smokers and female smokers are there
male=len(sex)-np.sum(sex)

In [103]:
male

87.0

In [104]:
female=len(sex)-male

In [105]:
female

157.0